### ISSUE TITLE
Meteor user logs out automatically after logging in...

### ISSUE THREAD

**Issue by smanji** [qnub/meteor-accounts-react-material-ui#1]
Firstly, thanks very much for contributing this component/package -- it seems to be exactly what I'm looking for; although, I'm running into a couple of issues utilizing it that I'm hoping you can help me with.

I'm using Meteor with React and React-Router. I've setup a route for the Login like so:

```
<Router history={ReactRouter.lib.BrowserHistory.history}>
        <Route name="home" path="/login" component={Accounts.ui.LoginFormSet}/>
</Router>
```

Using Material-UI, I have constructed a Toolbar within which I have included the Login and Logout buttons for this Meteor-Accounts-React-Material-UI package:

``` javascript
injectTapEventPlugin();
TopBar = React.createClass({  
  mixins: [ReactMeteorData],
  getInitialState: function() {
      return {};
  },
  getMeteorData() {
    return {
      currentUser: Meteor.user()
    };
  },
  childContextTypes: {
    muiTheme: React.PropTypes.object
  },
  getChildContext: function() {
    return {
      muiTheme: ThemeManager.getMuiTheme(Styles.LightRawTheme)
    };
  },
  render: function () {
    return (
      <Toolbar>
          {this.data.currentUser ? <RaisedButton label="Log Out" onClick={Meteor.logout()} /> : <RaisedButton label="Log In" linkButton={true} href="/login" />}
      </Toolbar>
    );
  }
});
```

When I click the Log In button, I'm routed to the Log In screen as expected. 

I'm experiencing two issues:
1. When I successfully login, after about 3 seconds, I'm automatically logged out. In my javascript console, I can type in Meteor.userId() immediately after logging in and I get back a value; however, after a few seconds, the login screen is displayed again and when I type in Meteor.userId() into the console I get back null.
2. When I successfully login, I'm presented with the Change Password screen. How do I specify to return back to the route I was on last before the Log In button was pressed? Your example showed passing a value to the redirect property of the Accounts.ui.LoginFormSet component in the context of FlowRouter; however, I'm not sure what I'm supposed to supply to this property in the context of React-Router -- is this component compatible with React-Router?

It would actually be great to see a sample application like the Meteor-React To Do list that incorporates this meteor-accounts-react-material-ui component.

Thank you in advance!
- Sadiq

**Comment by qnub** [comment]
**First.** In events you should use function as parameter, but not call it. So change:

```
<RaisedButton label="Log Out" onClick={Meteor.logout()} />
```

to

```
<RaisedButton label="Log Out" onClick={Meteor.logout} />
```

I see it's my mistake. I'll fix README. Also you can do somethinsg like that:

```
<RaisedButton label="Log Out" onClick={this.handleLogout} />
```

And add `handleLogout` to your parent component. Where you can unauthenticate user and make additional stuff…

**Second.** `Accounts.ui.LoginFormSet` can get optional property `redirect` like that (it's exists in README):

```
 <Accounts.ui.LoginFormSet redirect={this.handleLogin}/>
```

where `this.handleLogin` is callback function which will be called after sucsessfull login. So here you can made redirect user to desired URL.

**Comment by smanji** [comment]
Hi Vadim,

Thanks, your solution to #1 resolved my auto-logout issue.

However, I can't seem to implement #2 with react-router: when specifying
the component to use for a route, there doesn't seem to be a way to set the
redirect property like you can with FlowRouter.

Is it safe to say that this the Accounts.ui.LoginFormSet does not fully
support react-router as far as being able to specify the redirect property?

Thanks!
Sadiq

**Comment by smanji** [comment]
I think I'm getting closer, but now I believe it's more of an issue of how react-router works.

I'm wrapping the Accounts.ui.LoginFormSet component with a new component that can supply the redirect property.

However, I don't know how to have the function I pass into redirect actually perform a redirect with react-router! Furthermore, I would like to be able to capture the equivalent of the referrer (i.e. the page or route that called the /login route) and I would like to redirect the user back to that route.

Any ideas? (short of switching to FlowRouter...) 

``` javascript
var LoginWrapper = React.createClass({
  handleLogin: function() {
    //what do I put in here?
  },
  render: function () {
    return (
        <Accounts.ui.LoginFormSet redirect={this.handleLogin}/>    
    );
  }
});

Routes = React.createClass({  
  getInitialState: function() {
    return {};
  },
  render: function () {
    return (
      <Router history={browserHistory}>
        <Route name="home" path="/login" component={LoginWrapper}/>
      </Router>
    );
  }
});
```

**Comment by qnub** [comment]
I use flow-router with react layout, and it's very useful solution. Your wrapper can be something like that: can be something like that:

```
var LoginWrapper = React.createClass({
  handleLogin: function() {
      // redirect through ReactRouter if it have ability or through window:
      window.location.href = this.targetUrl;
  },
  render: function () {
    this.targetUrl = window.location.href; // save target URL from window on through ReactRouter if it have ability
    return (
        <Accounts.ui.LoginFormSet redirect={this.handleLogin}/>    
    );
  }
});
```

**Comment by qnub** [comment]
And yes `Accounts.ui.LoginFormSet` not support any routers (including `react-router`) to not interfere with existed one in project. Also `accounts-base`, on which is based my package, use own hardcoded routes based on Meteor's core functionality.

**Comment by smanji** [comment]
That did it! Thanks very much for your help! I may look at FlowRouter, but for the moment, this is now working for me.

**Comment by qnub** [comment]
Good news! :+1:
